# Generated by Django 5.0.3 on 2024-04-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpapers', '0002_questionpaper_delete_textbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'ordering': ['-standard', 'exam']},
        ),
    ]
