# Generated by Django 5.0.3 on 2024-04-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ict',
            options={'ordering': ['-date_added'], 'verbose_name': 'ICT and Simulation Site', 'verbose_name_plural': 'ICT and Simulation Sites'},
        ),
    ]
