# Generated by Django 5.0.3 on 2024-04-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tlm',
            options={'verbose_name': 'TLM Photo', 'verbose_name_plural': 'TLM Photos'},
        ),
    ]
