# Generated by Django 5.0.3 on 2024-04-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingvideos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingvideo',
            options={'ordering': ['standard', 'date_added'], 'verbose_name': 'Teaching Video', 'verbose_name_plural': 'Teaching Videos'},
        ),
    ]
