# Generated by Django 5.0.3 on 2024-04-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='link',
            field=models.URLField(default='https://quizizz.com/admin/quiz/66267f4d7e82d26920c4f8b8?source=quiz_share'),
        ),
    ]
