# Generated by Django 5.0.3 on 2024-04-20 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField(choices=[(10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1), (11, 11), (12, 12)], verbose_name='class')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='files')),
                ('exam', models.CharField(choices=[('FA1', 'FA1'), ('FA2', 'FA2'), ('FA3', 'FA3'), ('FA4', 'FA4'), ('SA1', 'SA1'), ('SA2', 'SA2'), ('PREPUBLIC', 'PREPUBLIC'), ('PUBLIC', 'PUBLIC')], max_length=10)),
                ('year', models.CharField(choices=[('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Principles of Valuation',
                'verbose_name_plural': 'Principles of Valuation',
            },
        ),
    ]
