# Generated by Django 5.0.3 on 2024-04-23 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='your name')),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^(\\+?\\d{1,3})?[-.\\s]?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')])),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('school', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Village/town')),
                ('mandal', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('field', models.CharField(choices=[('ICT IN EDUCATION', 'ICT IN EDUCATION'), ('IF PANELS', 'IF PANELS'), ('BYJUS TABS', 'BYJUS TABS'), ('MODULE WRITING', 'MODULE WRITING'), ('ACADEMIC CALENDAR', 'ACADEMIC CALENDAR'), ('QUESTION PAPER PREPARATION', 'QUESTION PAPER PREPARATION'), ('SIMULATIONS', 'SIMULATIONS'), ('VIDEO PREPARATION', 'VIDEO PREPARATION'), ('OTHERS', 'OTHERS')], max_length=100)),
                ('others', models.CharField(blank=True, max_length=200, verbose_name='If others, specify area')),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'Resource person',
                'verbose_name_plural': 'Resource persons',
                'ordering': ['district', 'mandal', 'field'],
            },
        ),
    ]
